# _config.yml

title: SPOCK Documentation
description: Documentation for the SPOCK project

## GitHub Pages base URL
#baseurl: "."   # Name of your GitHub repo (important!)

url: "https://username.github.io"
baseurl: "/SPOCK_v2"

# Files to include or exclude
include:
  - headers 
  - assets
  - /examples/tutorials/notebooks/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .github
  - DATABASE  # Add any other folders you want to exclude
  - .DS_Store
  - build
  - SPIRIT
  - SPOCK_files
  - TRAPPIST_schedules_docx
  - survey_hours
  - target_lists
  - eScheduler
  - SPOCK
  - dist
  - SPOCK.egg.info
  - local_files
  - night_blocks_propositions
  - old_docs_source
  - WG6_specific_timings
  - test.py
  - setup.py


# Optional: if you want pretty URLs
permalink: pretty

markdown: kramdown
highlighter: rouge